In [105]:
import pandas as pd


In [106]:
import numpy as np

In [107]:
# 1

dataList = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [108]:
dataListArray = np.array(dataList)

dataListArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
type(dataListArray), dataListArray.shape, dataListArray.ndim, dataListArray.dtype, dataListArray.nbytes

(numpy.ndarray, (10,), 1, dtype('int64'), 80)

In [110]:
# 2.1
np.ones((3,4)) * 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [111]:
# 2.2 [N/Improvement]
dataListTillFifty = np.arange(1,51)

In [112]:
reshape = dataListTillFifty.reshape(5,10)
reshape

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [113]:
# 3
a = [[1, 2], [3, 4]]
b = [[5, 6], [7, 8]]


In [114]:
aArray = np.array(a)
bArray = np.array(b)
aArray + bArray


array([[ 6,  8],
       [10, 12]])

In [115]:
aArray * bArray

array([[ 5, 12],
       [21, 32]])

In [116]:
# 4
firstRawList = [1, 2, 3, 4, 5, 6, 7, 8, 9]
secondRawList = [10, 20, 30, 40, 50]
firstRawListArray = np.array(firstRawList)
secondRawListArray = np.array(secondRawList)

In [117]:
# 4.1 [N/Improvement]
findEvenNum = firstRawListArray % 2 == 0
firstRawListArray[findEvenNum]

array([2, 4, 6, 8])

In [ ]:
# 4.2
fndOverThirty = secondRawListArray[secondRawListArray > 30]


In [123]:
chgOverThirtyToZero = secondRawListArray[secondRawListArray > 30]


In [122]:
editedArray = secondRawListArray[chgOverThirtyToZero]

In [124]:
# 5
randomArray = np.random.randint(1, 100, 9)

In [126]:
reshapeRandomArray = randomArray.reshape(3,3)
reshapeRandomArray

array([[46, 35, 54],
       [ 3, 88, 78],
       [85, 89, 59]])

In [ ]:
# 5.1
reshapeRandomArray.max(), reshapeRandomArray.min(), reshapeRandomArray.mean(), reshapeRandomArray.std()

(89, 3, 59.666666666666664, 27.243755655603398)

In [129]:
# 5.2
reshapeRandomArray.max(axis=0), reshapeRandomArray.min(axis=0), reshapeRandomArray.mean(axis=0), reshapeRandomArray.sum(axis=0)

(array([85, 89, 78]),
 array([ 3, 35, 54]),
 array([44.66666667, 70.66666667, 63.66666667]),
 array([134, 212, 191]))

In [130]:
reshapeRandomArray.max(axis=1), reshapeRandomArray.min(axis=1), reshapeRandomArray.mean(axis=1), reshapeRandomArray.sum(axis=1)

(array([54, 88, 89]),
 array([35,  3, 59]),
 array([45.        , 56.33333333, 77.66666667]),
 array([135, 169, 233]))

In [131]:
# 6
secondRandomArray = np.random.randint(1, 50, 25)
reshapeSecondRandomArray = secondRandomArray.reshape(5,5)
reshapeSecondRandomArray



array([[46, 12, 26, 43, 26],
       [14, 48, 17, 12, 43],
       [15, 43, 48,  4, 47],
       [47, 30,  6, 34, 41],
       [25, 30, 29, 17,  9]])

In [ ]:
# 6.1 나머지는 % N/Improvement
secondFindEvenNum = (reshapeSecondRandomArray % 2 == 0)
secondFindEvenNum

array([[ True,  True,  True, False,  True],
       [ True,  True, False,  True, False],
       [False, False,  True,  True, False],
       [False,  True,  True,  True, False],
       [False,  True, False, False, False]])

In [136]:
# 6.2
onlyEvenNum = reshapeSecondRandomArray[secondFindEvenNum]
onlyEvenNum

array([46, 12, 26, 26, 14, 48, 12, 48,  4, 30,  6, 34, 30])

In [137]:
# 7
thirdList = [1, 4, 9, 16, 25]
fourthList = [1, 2, 3, 4]
thirdListArray = np.array(thirdList)
fourthListArray = np.array(fourthList)

In [140]:
# 7.1 루트를 어떻게 표현할까? N/Improvement, 플러스 마이너스를 어떻게?
thirdListSqrt = np.sqrt(thirdListArray)
thirdListSqrt

array([1., 2., 3., 4., 5.])

In [ ]:
# 7.2 
fourthListArray * 