### 기본 사칙 연산

In [53]:
import pandas as pd

In [54]:
import numpy as np

In [55]:
data_list_first = [1,2,3]
type(data_list_first), len(data_list_first)

(list, 3)

In [56]:
data_list_second = [4,5,6]

In [57]:
data_list_third = [-1,-2,-3]

In [58]:
data_list_first + data_list_second
# ㄱ. 리스트끼리 더하면 리스트로 반환 ㄴ. 나열

[1, 2, 3, 4, 5, 6]

In [59]:
data_list_third * 2
# 두줄이 나온다~, 해당하는 부분 자체를 증폭

[-1, -2, -3, -1, -2, -3]

### Array 연산


In [60]:
data_array_first = np.array(data_list_first)

In [61]:
type(data_array_first), len(data_array_first)

(numpy.ndarray, 3)

In [62]:
data_array_second = np.array(data_list_second)

In [63]:
data_array_first + data_array_second
# ㄱ. 배열끼리 더하면 배열로 반환 ㄴ. 더하기

array([5, 7, 9])

In [64]:
data_array_first / data_array_second
# ㄱ. 배열끼리 곱하면 배열로 반환 ㄴ. 나누기

array([0.25, 0.4 , 0.5 ])

In [65]:
data_array_first * data_array_second


array([ 4, 10, 18])

In [66]:
data_array_third = np.array(data_list_third)
data_array_third

array([-1, -2, -3])

In [67]:
data_array_first - data_array_third, data_array_third - data_array_first
# 순서를 지켜야 하는구나, 결과 값이 달라지는구나~

(array([2, 4, 6]), array([-2, -4, -6]))

### 브로드 캐스팅

In [68]:
data_array_third *2 # data_array_third * [2, 2, 2]
# 연산이 되는구나~

array([-2, -4, -6])

### 조건절 적용

In [69]:
cond_array_first = np.array([10,20,30])

In [70]:
conditions = cond_array_first > 10 # [10,20,30] > [10, 10, 10]

In [71]:
cond_array_first[cond_array_first > 10] # [10,20,30] & [False, True, True]
# 질문

array([20, 30])

In [72]:
conditions.all() # 구성 요소가 하나라도 False 가 있으면 False로

False

In [73]:
cond_array_second = np.array([20,20,30])
conditions_second = cond_array_second >= 20
conditions_second


array([ True,  True,  True])

In [74]:
conditions_second.all()

True

In [75]:
conditions_second.any() # 구성 요소 중 하나라도 True 가 있으면 True로

True

In [76]:
# conditions_third = (10 <cond_array_first < 30)
# conditions_third = cond_array_first > 10 & cond_array_first < 30
# conditions_third = (cond_array_first > 10 & cond_array_first < 30)

conditions_third = (cond_array_first > 10) & (cond_array_first < 30)

conditions_third

array([False,  True, False])

### 집계함수

In [77]:
aggregation_list_first = [[1,2],[3,4],[5,6],[7,8]]
# row = 4, column = 2
# [] 안에 있는 변수가 x,y 두개

In [78]:
aggregation_array_first = np.array(aggregation_list_first)
aggregation_array_first

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [79]:
# col, index로 되지 않고 axis로 하는 이유 차원이 무수히 많으니까
# aggregation_array_first.sum()
# aggregation_array_first.sum(axis=0) # column 세로 합
aggregation_array_first.sum(axis=1) # row 가로합


array([ 3,  7, 11, 15])

max(), mean(), median()

In [80]:
# aggregation_array_first.max
aggregation_array_first.max(axis=0)


array([7, 8])

In [81]:
aggregation_array_first.argmax(axis=0) # max값의 index

array([3, 3])

### 특수행열 생성

In [82]:
np.zeros((2,3)) # 2x3 행렬

array([[0., 0., 0.],
       [0., 0., 0.]])

In [83]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [84]:
np.eye(3) # 대각선 1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 행렬 정보 확인

In [85]:
aggregation_array_first.shape

(4, 2)

In [86]:
aggregation_array_first.ndim # 2차원, 차원수

2

In [87]:
aggregation_array_first.dtype

dtype('int64')

In [88]:
aggregation_array_first.size

8

In [89]:
aggregation_array_first.nbytes, aggregation_array_first.itemsize * aggregation_array_first.size # 요소의 전체 바이트 사이즈

(64, 64)

In [90]:
array_float = aggregation_array_first.astype(np.float128) # 데이터 타입 변환

In [91]:
array_float.shape, array_float.dtype, array_float.nbytes # 데이터를 줄인다, 데이터 원자화, AI 에서 데이터를 줄이는 이유

((4, 2), dtype('float128'), 128)

### Merge
- stack(), concatenate()

In [92]:
merge_array_first = np.array(([1,2], [3,4]))
merge_array_second = np.array(([5,6], [7,8]))
merge_array_third = np.array(([10,11], [12,13], [14,15]))

In [93]:
merge_array_first.shape, merge_array_second.shape, merge_array_third.shape

((2, 2), (2, 2), (3, 2))

In [94]:
np.concatenate((merge_array_second, merge_array_third), axis=0) # 어디쪽에 기술되느냐

array([[ 5,  6],
       [ 7,  8],
       [10, 11],
       [12, 13],
       [14, 15]])

In [95]:
# 에러 나는 이유 붙는 면의 개수가 달라서 np.concatenate((merge_array_second, merge_array_third), axis=1) 
np.concatenate((merge_array_second, merge_array_first), axis=1)

array([[5, 6, 1, 2],
       [7, 8, 3, 4]])

### 차원 연산

In [96]:
# 벡터 연산 : dot product, 내적, inner product
# first = [3,4]
# second = [2,1]
first = [3,4,5]
second = [2,1,1]

array_first = np.array(first)
array_second = np.array(second)

dot_product_result = np.dot(array_first, array_second)
dot_product_result, type(dot_product_result)


(15, numpy.int64)

In [97]:
array_first, type(array_first), array_first.T.shape, array_first.shape # transpose 해도 표시가 동일하게 나오지만, transpose는 여전히 가능하다, 벡터는 열이다

(array([3, 4, 5]), numpy.ndarray, (3,), (3,))